## This file is part of Invenio.
## Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008, 2010, 2011, 2012 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""Invenio Search Engine config parameters."""

__revision__ = \
    "$Id$"

## Note: many interesting search engine config variables are defined
## in the global config.py.  This file should define locally
## interesting variables only.

## do we want experimental features? (0=no, 1=yes)
CFG_EXPERIMENTAL_FEATURES = 0

## CFG_WEBSEARCH_IDXPAIRS_FIELDS -- a comma separated list of index
## fields. This list contains all the index fields on which exact
## phrase search should use idxPairs tables.
CFG_WEBSEARCH_IDXPAIRS_FIELDS = ['global','abstract','title','caption']

## CFG_WEBSEARCH_IDXPAIRS_EXACT_SEARCH -- if true, it will eliminate
## all the false positives when using the word pairs for search.
## (Example: `foo bar baz' being search as `foo bar' and `bar baz' may
## lead to false positives if there is no second-pass.)  FIXME: we
## need this to be defined per index if we want to eliminate
## single-quoted vs double-quoted search difference, e.g. False for
## title search, but True for report number search.
CFG_WEBSEARCH_IDXPAIRS_EXACT_SEARCH = False

## Maximum number of collections to be displayed on the search results
## page. All the rest of the collections will be hidden by a
## "See more collections" link.
CFG_WEBSEARCH_RESULTS_OVERVIEW_MAX_COLLS_TO_PRINT = 10

## Prefix used for search results cache.
CFG_SEARCH_RESULTS_CACHE_PREFIX = "search_results::"

class InvenioWebSearchUnknownCollectionError(Exception):
    """Exception for bad collection."""
    def __init__(self, colname):
        """Initialisation."""
        self.colname = colname
    def __str__(self):
        """String representation."""
        return repr(self.colname)

class InvenioWebSearchWildcardLimitError(Exception):
    """Exception raised when query limit reached."""
    def __init__(self, res):
        """Initialization."""
        self.res = res

## CERN Site hack
#CFG_WEBSEARCH_SEARCH_WITHIN = ['title',
#                               'author',
#                               'abstract',
#                               'report number,
#                               'year']

CFG_WEBSEARCH_SEARCH_WITHIN = ['title',
                               'author',
                               'abstract',
#                                'keyword',
#                                'report number',
#                                'journal',
                               'year',
                               'fulltext',
#                                'reference',
                               'subject']


CFG_WEBSEACH_MATCHING_TYPES = [
        {
        'code': 'a',
        'title': "all of the words",
        'order': 1,
        'tokenize': """
            var vals = val.split(' '),
                result = $.map(vals, function(e) {
              return f+e;
            }).join(' AND ');
            if (vals.length > 1) {
                result = '(' + result +')';
            }
            return result;
        """
        },
        {
        'code': 'o',
        'title': "any of the words",
        'order': 2,
        'tokenize': """
            var vals = val.split(' '),
                result = $.map(vals, function(e) {
              return f+e;
            }).join(' OR ');
            if (vals.length > 1) {
                result = '(' + result +')';
            }
            return result;
        """
        },
        {
        'code': 'e',
        'title': "exact phrase",
        'order': 3,
        'tokenize': """
            return f+'"'+val+'"';
        """
        },
        {
        'code': 'p',
        'title': "partial phrase",
        'order': 4,
        'tokenize': """
            return f+"'"+val+"'";
        """
        },
        {
        'code': 'r',
        'title': "regular expression",
        'order': 5,
        'tokenize': """
            return f+'/'+val+'/';
        """
        }
    ]

CFG_LANGUAGE_DICT = {'aar': 'Afar',
 'abk': 'Abkhazian',
 'ace': 'Achinese',
 'ach': 'Acoli',
 'ada': 'Adangme',
 'ady': 'Adyghe',
 'afh': 'Afrihili',
 'afr': 'Afrikaans',
 'ain': 'Ainu (Japan)',
 'aka': 'Akan',
 'akk': 'Akkadian',
 'alb': 'Albanian',
 'sqi': 'Albanian',
 'ale': 'Aleut',
 'alt': 'Southern Altai',
 'amh': 'Amharic',
 'ang': 'Old English (ca. 450-1100)',
 'anp': 'Angika',
 'ara': 'Arabic',
 'arc': 'Official Aramaic (700-300 BCE)',
 'arg': 'Aragonese',
 'arm': 'Armenian',
 'hye': 'Armenian',
 'arn': 'Mapudungun',
 'arp': 'Arapaho',
 'arw': 'Arawak',
 'asm': 'Assamese',
 'ast': 'Asturian',
 'ava': 'Avaric',
 'ave': 'Avestan',
 'awa': 'Awadhi',
 'aym': 'Aymara',
 'aze': 'Azerbaijani',
 'bak': 'Bashkir',
 'bal': 'Baluchi',
 'bam': 'Bambara',
 'ban': 'Balinese',
 'baq': 'Basque',
 'eus': 'Basque',
 'bas': 'Basa (Cameroon)',
 'bej': 'Beja',
 'bel': 'Belarusian',
 'bem': 'Bemba (Zambia)',
 'ben': 'Bengali',
 'bho': 'Bhojpuri',
 'bik': 'Bikol',
 'bin': 'Bini',
 'bis': 'Bislama',
 'bla': 'Siksika',
 'bod': 'Tibetan',
 'tib': 'Tibetan',
 'bos': 'Bosnian',
 'bra': 'Braj',
 'bre': 'Breton',
 'bua': 'Buriat',
 'bug': 'Buginese',
 'bul': 'Bulgarian',
 'bur': 'Burmese',
 'mya': 'Burmese',
 'byn': 'Bilin',
 'cad': 'Caddo',
 'cam': 'Cambodian',
 'car': 'Galibi Carib',
 'cat': 'Catalan',
 'ceb': 'Cebuano',
 'cha': 'Chamorro',
 'chb': 'Chibcha',
 'che': 'Chechen',
 'chg': 'Chagatai',
 'chi': 'Chinese',
 'zho': 'Chinese',
 'chk': 'Chuukese',
 'chm': 'Mari (Russia)',
 'chn': 'Chinook jargon',
 'cho': 'Choctaw',
 'chp': 'Chipewyan',
 'chr': 'Cherokee',
 'chu': 'Church Slavic',
 'chv': 'Chuvash',
 'chy': 'Cheyenne',
 'cop': 'Coptic',
 'cor': 'Cornish',
 'cos': 'Corsican',
 'cre': 'Cree',
 'crh': 'Crimean Tatar',
 'csb': 'Kashubian',
 'cze': 'Czech',
 'ces': 'Czech',
 'dak': 'Dakota',
 'dan': 'Danish',
 'dar': 'Dargwa',
 'del': 'Delaware',
 'den': 'Slave (Athapascan)',
 'dgr': 'Dogrib',
 'din': 'Dinka',
 'div': 'Dhivehi',
 'doi': 'Dogri',
 'dsb': 'Lower Sorbian',
 'dua': 'Duala',
 'dum': 'Middle Dutch (ca. 1050-1350)',
 'dut': 'Dutch',
 'nld': 'Dutch',
 'dyu': 'Dyula',
 'dzo': 'Dzongkha',
 'efi': 'Efik',
 'egy': 'Egyptian (Ancient)',
 'eka': 'Ekajuk',
 'elx': 'Elamite',
 'eng': 'English',
 'enm': 'Middle English (1100-1500)',
 'epo': 'Esperanto',
 'est': 'Estonian',
 'ewe': 'Ewe',
 'ewo': 'Ewondo',
 'fan': 'Fang (Equatorial Guinea)',
 'fao': 'Faroese',
 'fat': 'Fanti',
 'fij': 'Fijian',
 'fil': 'Filipino',
 'fin': 'Finnish',
 'fon': 'Fon',
 'fre': 'French',
 'fra': 'French',
 'frm': 'Middle French (ca. 1400-1600)',
 'fro': 'Old French (842-ca. 1400)',
 'frr': 'Northern Frisian',
 'frs': 'Eastern Frisian',
 'fry': 'Western Frisian',
 'ful': 'Fulah',
 'fur': 'Friulian',
 'gaa': 'Ga',
 'gay': 'Gayo',
 'gba': 'Gbaya (Central African Republic)',
 'geo': 'Georgian',
 'kat': 'Georgian',
 'ger': 'German',
 'deu': 'German',
 'gez': 'Geez',
 'gil': 'Gilbertese',
 'gla': 'Scottish Gaelic',
 'gle': 'Irish',
 'glg': 'Galician',
 'glv': 'Manx',
 'gmh': 'Middle High German (ca. 1050-1500)',
 'goh': 'Old High German (ca. 750-1050)',
 'gon': 'Gondi',
 'gor': 'Gorontalo',
 'got': 'Gothic',
 'grb': 'Grebo',
 'grc': 'Ancient Greek (to 1453)',
 'gre': 'Greek',
 'ell': 'Greek',
 'grn': 'Guarani',
 'gsw': 'Swiss German',
 'guj': 'Gujarati',
 'gwi': 'Gwich\xca\xbcin',
 'hai': 'Haida',
 'hat': 'Haitian',
 'hau': 'Hausa',
 'haw': 'Hawaiian',
 'heb': 'Hebrew',
 'her': 'Herero',
 'hil': 'Hiligaynon',
 'hin': 'Hindi',
 'hit': 'Hittite',
 'hmn': 'Hmong',
 'hmo': 'Hiri Motu',
 'hrv': 'Croatian',
 'hsb': 'Upper Sorbian',
 'hun': 'Hungarian',
 'hup': 'Hupa',
 'iba': 'Iban',
 'ibo': 'Igbo',
 'ice': 'Icelandic',
 'isl': 'Icelandic',
 'ido': 'Ido',
 'iii': 'Sichuan Yi',
 'iku': 'Inuktitut',
 'ile': 'Interlingue',
 'ilo': 'Iloko',
 'ina': 'Interlingua',
 'ind': 'Indonesian',
 'inh': 'Ingush',
 'ipk': 'Inupiaq',
 'ita': 'Italian',
 'jav': 'Javanese',
 'jbo': 'Lojban',
 'jpn': 'Japanese',
 'jpr': 'Judeo-Persian',
 'jrb': 'Judeo-Arabic',
 'kaa': 'Kara-Kalpak',
 'kab': 'Kabyle',
 'kac': 'Kachin',
 'kal': 'Kalaallisut',
 'kam': 'Kamba (Kenya)',
 'kan': 'Kannada',
 'kas': 'Kashmiri',
 'kau': 'Kanuri',
 'kaw': 'Kawi',
 'kaz': 'Kazakh',
 'kbd': 'Kabardian',
 'kha': 'Khasi',
 'khm': 'Central Khmer',
 'kho': 'Khotanese',
 'kik': 'Kikuyu',
 'kin': 'Kinyarwanda',
 'kir': 'Kirghiz',
 'kmb': 'Kimbundu',
 'kok': 'Konkani',
 'kom': 'Komi',
 'kon': 'Kongo',
 'kor': 'Korean',
 'kos': 'Kosraean',
 'kpe': 'Kpelle',
 'krc': 'Karachay-Balkar',
 'krl': 'Karelian',
 'kru': 'Kurukh',
 'kua': 'Kuanyama',
 'kum': 'Kumyk',
 'kur': 'Kurdish',
 'kut': 'Kutenai',
 'lad': 'Ladino',
 'lah': 'Lahnda',
 'lam': 'Lamba',
 'lao': 'Lao',
 'lat': 'Latin',
 'lav': 'Latvian',
 'lez': 'Lezghian',
 'lim': 'Limburgan',
 'lin': 'Lingala',
 'lit': 'Lithuanian',
 'lol': 'Mongo',
 'loz': 'Lozi',
 'ltz': 'Luxembourgish',
 'lua': 'Luba-Lulua',
 'lub': 'Luba-Katanga',
 'lug': 'Ganda',
 'lui': 'Luiseno',
 'lun': 'Lunda',
 'luo': 'Luo (Kenya and Tanzania)',
 'lus': 'Lushai',
 'mac': 'Macedonian',
 'mkd': 'Macedonian',
 'mad': 'Madurese',
 'mag': 'Magahi',
 'mah': 'Marshallese',
 'mai': 'Maithili',
 'mak': 'Makasar',
 'mal': 'Malayalam',
 'man': 'Mandingo',
 'mao': 'Maori',
 'mri': 'Maori',
 'mar': 'Marathi',
 'mas': 'Masai',
 'may': 'Malay',
 'msa': 'Malay',
 'mdf': 'Moksha',
 'mdr': 'Mandar',
 'men': 'Mende (Sierra Leone)',
 'mga': 'Middle Irish (900-1200)',
 'mic': "Mi'kmaq",
 'min': 'Minangkabau',
 'mlg': 'Malagasy',
 'mlt': 'Maltese',
 'mnc': 'Manchu',
 'mni': 'Manipuri',
 'moh': 'Mohawk',
 'mon': 'Mongolian',
 'mos': 'Mossi',
 'mus': 'Creek',
 'mwl': 'Mirandese',
 'mwr': 'Marwari',
 'myv': 'Erzya',
 'nap': 'Neapolitan',
 'nau': 'Nauru',
 'nav': 'Navajo',
 'nbl': 'South Ndebele',
 'nde': 'North Ndebele',
 'ndo': 'Ndonga',
 'nds': 'Low German',
 'nep': 'Nepali',
 'new': 'Newari',
 'nia': 'Nias',
 'niu': 'Niuean',
 'nno': 'Norwegian Nynorsk',
 'nob': 'Norwegian Bokm\xc3\xa5l',
 'nog': 'Nogai',
 'non': 'Old Norse',
 'nor': 'Norwegian',
 'nqo': "N'Ko",
 'nso': 'Pedi',
 'nwc': 'Classical Newari',
 'nya': 'Nyanja',
 'nym': 'Nyamwezi',
 'nyn': 'Nyankole',
 'nyo': 'Nyoro',
 'nzi': 'Nzima',
 'oci': 'Occitan (post 1500)',
 'oji': 'Ojibwa',
 'ori': 'Oriya',
 'orm': 'Oromo',
 'osa': 'Osage',
 'oss': 'Ossetian',
 'ota': 'Ottoman Turkish (1500-1928)',
 'pag': 'Pangasinan',
 'pal': 'Pahlavi',
 'pam': 'Pampanga',
 'pan': 'Panjabi',
 'pap': 'Papiamento',
 'pau': 'Palauan',
 'peo': 'Old Persian (ca. 600-400 B.C.)',
 'per': 'Persian',
 'fas': 'Persian',
 'phn': 'Phoenician',
 'pli': 'Pali',
 'pol': 'Polish',
 'pon': 'Pohnpeian',
 'por': 'Portuguese',
 'pro': 'Old Proven\xc3\xa7al (to 1500)',
 'pus': 'Pushto',
 'que': 'Quechua',
 'raj': 'Rajasthani',
 'rap': 'Rapanui',
 'rar': 'Rarotongan',
 'roh': 'Romansh',
 'rom': 'Romany',
 'rum': 'Romanian',
 'ron': 'Romanian',
 'run': 'Rundi',
 'rup': 'Macedo-Romanian',
 'rus': 'Russian',
 'sad': 'Sandawe',
 'sag': 'Sango',
 'sah': 'Yakut',
 'sam': 'Samaritan Aramaic',
 'san': 'Sanskrit',
 'sas': 'Sasak',
 'sat': 'Santali',
 'scn': 'Sicilian',
 'sco': 'Scots',
 'sel': 'Selkup',
 'sga': 'Old Irish (to 900)',
 'shn': 'Shan',
 'sid': 'Sidamo',
 'sin': 'Sinhala',
 'slk': 'Slovak',
 'slo': 'Slovak',
 'slv': 'Slovenian',
 'sma': 'Southern Sami',
 'sme': 'Northern Sami',
 'smj': 'Lule Sami',
 'smn': 'Inari Sami',
 'smo': 'Samoan',
 'sms': 'Skolt Sami',
 'sna': 'Shona',
 'snd': 'Sindhi',
 'snk': 'Soninke',
 'sog': 'Sogdian',
 'som': 'Somali',
 'sot': 'Southern Sotho',
 'spa': 'Spanish',
 'srd': 'Sardinian',
 'srn': 'Sranan Tongo',
 'srp': 'Serbian',
 'srr': 'Serer',
 'ssw': 'Swati',
 'suk': 'Sukuma',
 'sun': 'Sundanese',
 'sus': 'Susu',
 'sux': 'Sumerian',
 'swa': 'Swahili',
 'swe': 'Swedish',
 'syc': 'Classical Syriac',
 'syr': 'Syriac',
 'tah': 'Tahitian',
 'tam': 'Tamil',
 'tat': 'Tatar',
 'tel': 'Telugu',
 'tem': 'Timne',
 'ter': 'Tereno',
 'tet': 'Tetum',
 'tgk': 'Tajik',
 'tgl': 'Tagalog',
 'tha': 'Thai',
 'tib': 'Tibetan',
 'bod': 'Tibetan',
 'tig': 'Tigre',
 'tir': 'Tigrinya',
 'tiv': 'Tiv',
 'tkl': 'Tokelau',
 'tlh': 'Klingon',
 'tli': 'Tlingit',
 'tmh': 'Tamashek',
 'tog': 'Tonga (Nyasa)',
 'ton': 'Tonga (Tonga Islands)',
 'tpi': 'Tok Pisin',
 'tsi': 'Tsimshian',
 'tsn': 'Tswana',
 'tso': 'Tsonga',
 'tuk': 'Turkmen',
 'tum': 'Tumbuka',
 'tur': 'Turkish',
 'tvl': 'Tuvalu',
 'twi': 'Twi',
 'tyv': 'Tuvinian',
 'udm': 'Udmurt',
 'uga': 'Ugaritic',
 'uig': 'Uighur',
 'ukr': 'Ukrainian',
 'umb': 'Umbundu',
 'urd': 'Urdu',
 'uzb': 'Uzbek',
 'vai': 'Vai',
 'ven': 'Venda',
 'vie': 'Vietnamese',
 'vol': 'Volap\xc3\xbck',
 'vot': 'Votic',
 'wal': 'Wolaytta',
 'war': 'Waray (Philippines)',
 'was': 'Washo',
 'wel': 'Welsh',
 'cym': 'Welsh',
 'wln': 'Walloon',
 'wol': 'Wolof',
 'xal': 'Kalmyk',
 'xho': 'Xhosa',
 'yao': 'Yao',
 'yap': 'Yapese',
 'yid': 'Yiddish',
 'yor': 'Yoruba',
 'zap': 'Zapotec',
 'zbl': 'Blissymbols',
 'zen': 'Zenaga',
 'zha': 'Zhuang',
 'zul': 'Zulu',
 'zun': 'Zuni',
 'zza': 'Zaza',
 'en': 'English',
 'ge': 'German',
 'gr': 'Greek',
 'fr': 'French',
 }

CFG_STOPWORDS_EN = ["a",'able',"about","across","after",'all','almost','also',
                    'am','among','an','and','any','are','as','at','be',
                    'because','been','but','by','can','cannot','could','dear',
                    'did','do','does','either','else','ever','every','for',
                    'from','get','got','had','has','have','he','her','hers',
                    'him','his','how','however','i','if','in','into','is','it',
                    'its','just','least','let','like','likely','may','me',
                    'might','most','must','my','neither','no','nor','not','of',
                    'off','often','on','only','or','other','our','own','rather',
                    'said','say','says','she','should','since','so','some',
                    'than','that','the','their','them','then','there','these',
                    'they','this','tis','to','too','twas','us','wants','was',
                    'we','were','what','when','where','which','while','who',
                    'whom','why','will','with','would','yet','you','your']

CFG_STOPWORDS_ES = ['alg\xc3\xban', 'alguna', 'algunas', 'alguno', 'algunos',
                    'ambos', 'ampleamos', 'ante', 'antes', 'aquel', 'aquellas',
                    'aquellos', 'aqui', 'arriba', 'atras', 'bajo', 'bastante',
                    'bien', 'cada', 'cierta', 'ciertas', 'cierto', 'ciertos',
                    'como', 'con', 'conseguimos', 'conseguir', 'consigo',
                    'consigue', 'consiguen', 'consigues', 'cual', 'cuando',
                    'dentro', 'desde', 'donde', 'dos', 'el', 'ellas', 'ellos',
                    'en', 'encima', 'entonces', 'entre', 'era', 'eramos', 'eran',
                    'eras', 'eres', 'es', 'esta', 'estaba', 'estado', 'estais',
                    'estamos', 'estan', 'estoy', 'fin', 'fue', 'fueron', 'fui',
                    'fuimos', 'gueno', 'ha', 'hace', 'haceis', 'hacemos',
                    'hacen', 'hacer', 'haces', 'hago', 'incluso', 'intenta',
                    'intentais', 'intentamos', 'intentan', 'intentar', 'intentas',
                    'intento', 'ir', 'la', 'largo', 'las', 'lo', 'los',
                    'mientras', 'mio', 'modo', 'muchos', 'muy', 'nos', 'nosotros',
                    'otro', 'para', 'pero', 'podeis', 'podemos', 'poder', 'podria',
                    'podriais', 'podriamos', 'podrian', 'podrias', 'por',
                    'por qu\xc3\xa9', 'porque', 'primero', 'puede', 'pueden',
                    'puedo', 'quien', 'sabe', 'sabeis', 'sabemos', 'saben', 'saber',
                    'sabes', 'ser', 'si', 'siendo', 'sin', 'sobre', 'sois',
                    'solamente', 'solo', 'somos', 'soy', 'su', 'sus',
                    'tambi\xc3\xa9n', 'teneis', 'tenemos', 'tener', 'tengo',
                    'tiempo', 'tiene', 'tienen', 'todo', 'trabaja', 'trabajais',
                    'trabajamos', 'trabajan', 'trabajar', 'trabajas', 'trabajo',
                    'tras', 'tuyo', 'ultimo', 'un', 'una', 'unas', 'uno', 'unos',
                    'usa', 'usais', 'usamos', 'usan', 'usar', 'usas', 'uso', 'va',
                    'vais', 'valor', 'vamos', 'van', 'vaya', 'verdad', 'verdadera',
                    'verdadero', 'vosotras', 'vosotros', 'voy', 'yo']

CFG_STOPWORDS_FR = ['alors', 'au', 'aucuns', 'aussi', 'autre', 'avant', 'avec',
                    'avoir', 'bon', 'car', 'ce', 'cela', 'ces', 'ceux', 'chaque',
                    'ci', 'comme', 'comment', 'dans', 'des', 'du', 'dedans',
                    'dehors', 'depuis', 'deux', 'devrait', 'doit', 'donc', 'dos',
                    'droite', 'd\xc3\xa9but', 'elle', 'elles', 'en', 'encore',
                    'essai', 'est', 'et', 'eu', 'fait', 'faites', 'fois', 'font',
                    'force', 'haut', 'hors', 'ici', 'il', 'ils', 'je', 'juste',
                    'la', 'le', 'les', 'leur', 'l\xc3\xa0', 'ma', 'maintenant',
                    'mais', 'mes', 'mine', 'moins', 'mon', 'mot', 'm\xc3\xaame',
                    'ni', 'nomm\xc3\xa9s', 'notre', 'nous', 'nouveaux', 'ou',
                    'o\xc3\xb9', 'par', 'parce', 'parole', 'pas', 'personnes',
                    'peut', 'peu', 'pi\xc3\xa8ce', 'plupart', 'pour', 'pourquoi',
                    'quand', 'que', 'quel', 'quelle', 'quelles', 'quels', 'qui',
                    'sa', 'sans', 'ses', 'seulement', 'si', 'sien', 'son', 'sont',
                    'sous', 'soyez', 'sujet', 'sur', 'ta', 'tandis', 'tellement',
                    'tels', 'tes', 'ton', 'tous', 'tout', 'trop', 'tr\xc3\xa8s',
                    'tu', 'valeur', 'voie', 'voient', 'vont', 'votre', 'vous', 'vu',
                    '\xc3\xa7a', '\xc3\xa9taient', '\xc3\xa9tat', '\xc3\xa9tions',
                    '\xc3\xa9t\xc3\xa9', '\xc3\xaatre']

CFG_STOPWORDS = CFG_STOPWORDS_EN + CFG_STOPWORDS_ES + CFG_STOPWORDS_FR
